# Generated by Django 6.0.5 on 2026-05-29 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('logo', models.ImageField(upload_to='langs/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('lang_type', models.CharField(choices=[('ML', 'MACHINE'), ('HL', 'HUMAN'), ('AL', 'ABSTRACT')], max_length=2)),
            ],
        ),
    ]
