# Generated by Django 6.0.5 on 2026-05-29 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lang',
            name='description',
            field=models.TextField(verbose_name=''),
        ),
        migrations.AlterField(
            model_name='lang',
            name='lang_type',
            field=models.CharField(choices=[('COMPILED', 'Compiled Language'), ('INTERPRETED', 'Interpreted Language'), ('SYSTEM', 'System Programming Language')], max_length=20),
        ),
    ]
