# Generated by Django 6.0.5 on 2026-05-29 13:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langs', '0002_alter_lang_description_alter_lang_lang_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('launched_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('lang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lang_engine', to='langs.lang')),
            ],
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adapted_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('langs', models.ManyToManyField(related_name='langs', to='langs.lang')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('1', 'ONE STAR'), ('2', 'TWO STAR'), ('3', 'THREE STAR'), ('4', 'FOUR STAR'), ('5', 'FIVE START')], max_length=50)),
                ('comment', models.TextField(verbose_name='')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='langs.lang')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
