# Generated by Django 5.0.7 on 2024-07-31 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0002_remove_chaivariety_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='chaivariety',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
