# Generated by Django 5.0.7 on 2024-08-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_chaicertificate_chaireview_store'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chaicertificate',
            old_name='chai',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='chaireview',
            name='rating',
            field=models.TextField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=2),
        ),
    ]
